---
title: "UM"
author: "Chiel Wijs (s3199886)"
date: "24-10-2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

create an empty dataframe

```{r}
subject  <- rep(1:8, 40)
subject <- sort(subject)

block <- rep(c(rep(1, 20), rep(2, 20)), 8)

condition <- rep(c(rep(c(rep("AIDED", 20), rep("UNAIDED", 20)),2), rep(c(rep("UNAIDED", 20), rep("AIDED", 20)),2)), 2)

list <- rep(c(rep(1, 20), rep(2, 20), rep(2, 20), rep(1, 20)),4)

item <- rep(1:20, 16)

accuracy <- rep(0, 320)

df <- cbind(subject,block, condition, list, item, accuracy)

df <- data.frame(df)

df$subject <- as.factor(df$subject)
df$block <- as.factor(df$block)
df$condition <- as.factor(df$condition)
df$list <- as.factor(df$list)
df$item <- as.factor(df$item)
df$accuracy <- as.numeric(df$accuracy)
```

fill the data for each participant, fill in the scores for the first block first, and the second block second.  fill in 1 for a correct trial and 0 for an incorrect trial
```{r}
#subject 1
n <- 0
#block1
df$accuracy[(1+n*40):(20+n*40)] <- c(1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1)
#block2
df$accuracy[(21+n*40):(40+n*40)] <- c(0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1)

#subject 2
n <- 1
#block1
df$accuracy[(1+n*40):(20+n*40)] <- c(0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0)
#block2
df$accuracy[(21+n*40):(40+n*40)] <- c(1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1)

#subject 3
n <- 2
#block1
df$accuracy[(1+n*40):(20+n*40)] <- c(1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0)
#block2
df$accuracy[(21+n*40):(40+n*40)] <- c(1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1)

#subject 4
n <- 3
#block1
df$accuracy[(1+n*40):(20+n*40)] <- c(0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1)
#block2
df$accuracy[(21+n*40):(40+n*40)] <- c(1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1)

#subject 5
n <- 4
#block1
df$accuracy[(1+n*40):(20+n*40)] <- c(1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0)
#block2
df$accuracy[(21+n*40):(40+n*40)] <- c(0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1)

#subject 6
n <- 5
#block1
df$accuracy[(1+n*40):(20+n*40)] <- c(0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1)
#block2
df$accuracy[(21+n*40):(40+n*40)] <- c(1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0)

#subject 7
n <- 6
#block1
df$accuracy[(1+n*40):(20+n*40)] <- c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1)
#block2
df$accuracy[(21+n*40):(40+n*40)] <- c(0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1)

#subject 8
n <- 7
#block1
df$accuracy[(1+n*40):(20+n*40)] <- c(0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1)
#block2
df$accuracy[(21+n*40):(40+n*40)] <- c(1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0)
```

```{r}
library(lme4)
library(plotfunctions) #for se
library(plyr)
averages <- aggregate(accuracy ~ condition + subject, data = df, FUN = mean)
meanSe <- ddply(averages, c("condition"), summarize,
                meanAccuracy = mean(accuracy),
                seAccuracy = se(accuracy))

meanSe <- meanSe[order(meanSe$condition, decreasing = TRUE),]

table1 <- cbind(meanSe[meanSe$condition=="UNAIDED",]$meanAccuracy,
                meanSe[meanSe$condition=="AIDED",]$meanAccuracy)

colnames(table1) <- c("Unaided", "Aided")

bp <- barplot(table1, ylim=c(0,1), xlab = "Condition", ylab = "Accuracy",
              col = "lightgrey", font.lab=2,
              main= "Mean accuracy per condition")
errorBars(bp, meanSe$meanAccuracy, meanSe$seAccuracy)

#per participant
clrs = rainbow(8)

emptyPlot(c(0.7,2.3), c(0,1), h0=0,
main="accuracy", axes=FALSE, ylab="Intercept adjustment")

axis(2, las=1)
axis(1, at=c(1), tick=FALSE, font=2, labels="UNAIDED")
axis(1, at=c(2), tick=FALSE, font=2, labels="AIDED")

for(subj in 1:8) {
  
  points(1, averages[which(averages$subject==subj & averages$condition=="UNAIDED"),]$accuracy, col=clrs[subj], pch=19)

  points(2, averages[which(averages$subject==subj & averages$condition=="AIDED"),]$accuracy, col=clrs[subj], pch=19)
  
  lines(c(1,2),c(averages[which(averages$subject==subj & averages$condition=="UNAIDED"),]$accuracy ,averages[which(averages$subject==subj & averages$condition=="AIDED"),]$accuracy), col=clrs[subj])
}

legend("right", title="subj",legend= c(1:8), col = clrs, bty="n", pch=19)
```

```{r}
df$condition <- relevel(df$condition, ref='UNAIDED')

m1 <- glmer(accuracy ~ condition + (1|subject), data = df, family = binomial)
summary(m1)

m2 <- glmer(accuracy ~ condition + block + condition:block + (1|subject), data = df, family = binomial)
summary(m2)
```


